### ISSUE TITLE
Found genom, which breaks the whole simulaion

### ISSUE THREAD

**Issue by nikonru** [Slava2001/TorLand#1]
This genom breaks the whole simulation, your application freezes with multiple errors in the console.
`LXE5CBQAEAGILYK2JF3BCRN575B7MAA5OZRDM7XDHONOYDS2VCRJXTJGNJUPA7YTLKTW33QFVEZQT5QA`
![image](https://github.com/user-attachments/assets/e6303627-3b40-45dd-b77f-5eaee8d0cd94)

**Comment by Slava2001** [comment]
Зависание обусловлено ошибкой в резолвере меток. Минимальный код для воспроизведения (код должен заканчиваться меткой, которая используется хотя бы одной командой):
```
jmp next
next:
```
Так как метка заменяется адресом следующей за ней команды, последняя метка (за которой не следуют команды) заменяется адресом, который выходит за границу массива команд.  В данном случае код скомпилируется в
```
0: Jmp(1)
```
При выполнении кода, интерпиратор без проверок (тк ожидается, что все метки валидные) присвоить значение 1 счетчику команд и затем, попытается получить команду по этому адресу и выйдет за границу массива.

Это ошибка компилятора, тк он генерирует не валидный код. Для исправления в резолвер меток было добавлено деление адреса по модулю длины кода, то есть теперь код будет скомпилирован так:
```
0: Jmp(0)
```
Кроме того, был написан интегральный тест фиксирующий правильное поведение.

МР: https://github.com/Slava2001/TorLand/pull/2

Спасибо за участие в разработке!

**Comment by nikonru** [comment]
Thanks, but i don't understand Russian anyway, so it's completely cryptic for what you have written here.
